### ISSUE TITLE
simple questions about your code 

### ISSUE THREAD

**Issue by lxtGH** [kazuto1011/deeplab-pytorch#11]
Hi ! thanks for sharing your code. 
1, I want to know if the key(name) match the pretraind model in torch vision in your resnet models so that I can load the pretrained models
2,  I test your mode but I found the input and output scale  doesn't match. I haven't see the code in details, but based on my knowledge of semantic segmetation the input and output scale should match?  I didn't run on COCO,  I run some code on cityscapes,and VOC

**Comment by littlebelly** [comment]
@lxtGH 

1. Actually, deeplab use a resnet with dilated convolution layer which is different from the original resnet in torchvision, so, you can not load pretrained model from torchvision directly, and pretrained models of pytorch and caffe have different training process (like data preprocessing method), which makes it harder when you try to reimplement some caffe projects using pytorch, as you can see, the author of this repository used the parameters converted from caffemodel which which provided by the author of deeplab.

2. when I train on voc, it can run without problems, but the results is just ~71, which have some difference with the original paper

**Comment by kazuto1011** [comment]
1. Thanks for your comments @littlebelly. But I think the dilation does not matter for loading torchvision parameters if the keys match. The author of deeplab basically fine-tuned ImageNet params. Please try to change the dilation rates in my model and load a converted model. @lxtGH, I believe you can partially load the torchvision parameters  up to the ```layer5```. A problem here is in that the COCO-stuff training does not use the ImageNet params we can load from torchvision but their own init params (actually same thing as the VOC init model pre-trained on COCO). That's why I took this approach to load params from caffemodels.

2. @lxtGH, what do you mean by the "scale"? DeepLab v2 does not include the trainable upsampling process like SegNet and U-Net, so I think it's okay even if the sizes do not match in this dilated FCN scheme. Please let me know if I'm beside the point.

I'm sorry but I haven't checked the VOC results. The bug is weird anyway. Bilinear upsampling in PyTorch is slightly different from Caffe's one. I think that may be related to the results.
