### ISSUE TITLE
Pretrained weights for Deeplab v3 , v3+

### ISSUE THREAD

**Issue by sakshamjindal07** [kazuto1011/deeplab-pytorch#25]
Can anybody let me know how to port pretrained weights (provided by authors of paper) of V3 and V3+ in tensorflow to pytorch  ?

**Comment by Keson96** [comment]
The authors don't provide pretrained weights for ResNet backbone (only Xception and mobile net). [Here](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md) is a pretrained file but the structure of ResNet is slightly modified.
In terms of porting, please refer to [this](https://discuss.pytorch.org/t/how-to-transfer-pretained-model-from-tensorflow-to-pytorch/6173) for information. 
After an hour of searching, I could not find a good and clear way to do the porting. This seems a good question and I will look into it.

**Comment by kazuto1011** [comment]
Let me close this issue because I have no plan to implement porting the official v3/v3+ weights.
My other repository may help you to implement that. It includes the model definition of Google's ResNet v1/v2 and Xception v1. The weights are automatically converted from provided TensorFlow model and Keras model respectively.
https://github.com/kazuto1011/pytorch-ported-models/blob/master/models/classification/model_zoo.py
