### ISSUE TITLE
Issues about resize ground-truth

### ISSUE THREAD

**Issue by jason718** [kazuto1011/deeplab-pytorch#40]
During evaluation, shouldn't you resize the prediction to have the same size of ground-truth and compute these stats? I don't think change ground-truth is the correct thing to do ideally.

**Comment by kazuto1011** [comment]
The authors of coco-stuff pre-scale images and annotations to 513x513 size for both training and evaluation of ResNet backbone DeepLab. You can change the lines below with ground-truth size of ```labels```. Both have the same size.

https://github.com/kazuto1011/deeplab-pytorch/blob/6b395848753e6e3cdd04b1c1227b9e6581e34d4a/eval.py#L87-L89

**Comment by jason718** [comment]
Thanks for answering quick. I have contacted the authors. I'll leave this open till he replies.

**Comment by nightrome** [comment]
Hi. I agree with @jason718 that the correct behavior is to resize the predictions to full image size and perform evaluation there. Note however that the COCO images are close in size to 513x513, so the effect of this should be quite small. To make the results 100% comparable we provide the COCO devkit, evaluation server and [leaderboard](http://cocodataset.org/#stuff-leaderboard) so that you can exactly benchmark your method against the literature.

**Comment by kazuto1011** [comment]
Let me close this issue. To preserve the aspect ratio of ground truth, please set ```WARP_IMAGE: False``` in the config file.
