### ISSUE TITLE
VOC12

### ISSUE THREAD

**Issue by fabiopoiesi** [kazuto1011/deeplab-pytorch#50]
Hi Kazuto,

Are you planning to update your repo adding the full support for VOC12 dataset? Some parts have the possibility to configure it, some others not, i.e. get_dataset().

Thanks

**Comment by kazuto1011** [comment]
Okay, I will try to add a data loader for VOC12 and to train/test it. Although I had received such suggestions so far, I have not done that because many VOC12 implementations are available on GitHub. Some VOC12-related files are just for inference using the pre-trained model. It can be converted from caffemodel.

```bash
python convert.py --dataset voc12
```

**Comment by fabiopoiesi** [comment]
OK. This sounds great. It would be interesting to retrain the net on voc, starting from the coco init, and see the results compared to the original paper (as you did in the table for coco).

**Comment by kazuto1011** [comment]
Add [PASCAL VOC results](https://github.com/kazuto1011/deeplab-pytorch#performance).

**Comment by fabiopoiesi** [comment]
Thanks for the code.
Where can we get the pretrained model of coco v1?
data/models/coco/deeplabv1_resnet101/caffemodel/deeplabv1_resnet101-coco.pth

The ones of the links in the table a v2.

**Comment by kazuto1011** [comment]
Follow [this step](https://github.com/kazuto1011/deeplab-pytorch#initial-weights) to generated from the caffemodel.

**Comment by fabiopoiesi** [comment]
Yes. I did it and it is fine now.
