### ISSUE TITLE
ValueError: Expected input batch_size (182) to match target batch_size (2).

### ISSUE THREAD

**Issue by yejg2017** [kazuto1011/deeplab-pytorch#64]
When I run the deeplabv2 model on cocostuff164k, with batch_size=2,I get the error

#ValueError: Expected input batch_size (182) to match target batch_size (2).

And I check the output's  of model  is [2,182,41,41],and the labels'shape is [2,41,41],I think the problem is loss function.And I do not how to fix this issue.Could you help me ?Thanks

**Comment by kazuto1011** [comment]
Did you run that on multiple GPUs?

**Comment by yejg2017** [comment]
> Did you run that on multiple GPUs?

No,I only run that on single GPU

**Comment by kazuto1011** [comment]
Could you provide the command to reproduce the issue?

**Comment by toshas** [comment]
It is likely you instantiate a model with 2 output classes and attempt to load coco weights.

**Comment by kazuto1011** [comment]
Thank you @toshas. I think @yejg2017 modified the code and iterated over the tensor in `[2, 182, 41, 41]` instead of four-scale logits `4 x [2, 182, H, W]`. The error may be due to that the loss function received sliced `[182, 41, 41]` logit and `[2, 41, 41]` labels. Please check the tensor just before the loss function again. Don't switch the model to eval mode or don't remove MSC class, if you want to use the multi-scale training script intact. Please reopen this issue if someone still has the same problem and any additional information could be provided.
https://github.com/kazuto1011/deeplab-pytorch/blob/79cb3900bea41aa45cd9848bcd6b9e7e8177e6d0/main.py#L233-L237
