### ISSUE TITLE
Why do you set ceil_mode=True in the _Stem class of the file resnet.py?

### ISSUE THREAD

**Issue by cactusyh** [kazuto1011/deeplab-pytorch#80]
Thank you for your legible and powerful code! I've noticed that you set `ceil_mode=True` in the _Stem class of the file resnet.py, [here](https://github.com/kazuto1011/deeplab-pytorch/blob/f54ae1879bb1cfc2e1849699c6e929e200539b82/libs/models/resnet.py#L110). This will change the size of the output feature. I've noticed that the implementation of torchvision didn't use that, [here](https://github.com/pytorch/vision/blob/39021408587eb252ebb842a54195d840d6d76095/torchvision/models/resnet.py#L149). Do you have any special consideration to add this? Thank you so much.

**Comment by kazuto1011** [comment]
My ResNet modules are defined to match the original DeepLab v2 written in Caffe so that the training can start from a pre-trained caffemodel. The "ceil" pooling is from [here](https://bitbucket.org/aquariusjay/deeplab-public-ver2/src/071ef5a59aad8d9e6e1f5b8dff3d7a5c984a3d3a/src/caffe/layers/pooling_layer.cpp#lines-90:93) in the authors' Caffe. The bottleneck block is also different from the one in torchvision, on whether the strided-downsampling is in the 1st 1x1 or 2nd 3x3 convolution.
